@startuml

title __EXCEPTION's Class Diagram__\n

  namespace  {
    namespace om.carlos.costura {
      namespace domain.exception {
        class com.carlos.costura.domain.exception.AuthorizationException {
            {static} - serialVersionUID : long
            + AuthorizationException()
            + AuthorizationException()
        }
      }
    }
  }
  

  namespace  {
    namespace om.carlos.costura {
      namespace domain.exception {
        class com.carlos.costura.domain.exception.CustomExceptionHandler {
            - messageSource : MessageSource
            + authorization()
            + handleAmazonClientException()
            + handleAmazonS3Exception()
            + handleAmazonServiceException()
            + handleFileException()
            + handleNoSuchElementException()
            # handleMethodArgumentNotValid()
        }
      }
    }
  }
  

  namespace  {
    namespace om.carlos.costura {
      namespace domain.exception {
        class com.carlos.costura.domain.exception.Error {
            - error : String
            - message : String
            - path : String
            - status : Integer
            - timestamp : OffsetDateTime
            + Error()
            + Error()
            + equals()
            + getError()
            + getMessage()
            + getPath()
            + getStatus()
            + getTimestamp()
            + hashCode()
            + setError()
            + setMessage()
            + setPath()
            + setStatus()
            + setTimestamp()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.carlos.costura {
      namespace domain.exception {
        class com.carlos.costura.domain.exception.FileException {
            + FileException()
            + FileException()
        }
      }
    }
  }
  

  namespace  {
    namespace om.carlos.costura {
      namespace domain.exception {
        class com.carlos.costura.domain.exception.PageNotFoundException {
            - message : String
            + PageNotFoundException()
            + getMessage()
        }
      }
    }
  }
  

  com.carlos.costura.domain.exception.CustomExceptionHandler -up-|> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
