INSERT INTO users values(1, '2021-08-31 13:59:35.453600','Costureiro com vasta experiência em confecção de máscaras.','carlos@email.com','Carlos Eduardo Marangoni Mendes','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/carlos.jpg','carlos_marangoni');
INSERT INTO users values(2, '2021-08-30 13:59:35.453600','Revendedor de modelagens de vestido','darlan@email.com','Darlan Ricardo Marangoni da Silva','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/darlan.jpg','darlan_silva');
INSERT INTO users values(3, '2021-08-29 13:59:35.453600','Costureira com canal no youtube com mais de 1 milhão de inscritos.','maria@email.com','Maria Silva','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mari_costura.jpg','mari_costura');
INSERT INTO roles values(1,'ROLE_USER');
INSERT INTO roles values(2,'ROLE_ADMIN');
INSERT INTO roles values(3,'ROLE_CREATOR');
INSERT INTO users_roles values(1,2);
INSERT INTO users_roles values(2,1);
INSERT INTO users_roles values(3,3);
INSERT INTO category values (1,'CALCA');
INSERT INTO category values (2,'CAMISETA');
INSERT INTO category values (3,'LINGERIE');
INSERT INTO category values (4,'MASCARA');
INSERT INTO category values (5,'VESTIDO');
INSERT INTO post values(1,4,1,'2021-08-31 13:59:35.453600','Postagem de teste','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca1.png','Calça simples',1,1);
INSERT INTO post_item values(1,'Molde calca P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca1.png',25.2,1);
INSERT INTO post_item values(2,'Molde calca M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca1.png',30,1);
INSERT INTO post values(2,0,0,'2021-09-01 13:59:35.453600','Segunda postagem teste','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca2.jpg','Calça de couro',1,1);
INSERT INTO post_item values(1,'Molde calca P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca2.jpg',20,2);
INSERT INTO post_comments values(1,'comentario',4,1,2);
INSERT INTO post values(3,4,2,'2021-09-05 13:59:35.453600','terceira postagem teste','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca3.jpg','Calça jeans',1,2);
INSERT INTO post_comments(description,stars,post_id,user_id) values('Comentario teste',4,3,3);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca1.png',0,3);
INSERT INTO post values(4,0,0,'2021-08-31 13:59:35.453600','Quarta postagem de teste','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta1.jpg','Camiseta simples',2,1);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta1.jpg',25.2,4);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta1.jpg',30,4);
INSERT INTO post values(5,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 5','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta2.jpg','Regata simples',2,2);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta2.jpg',25.2,5);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta2.jpg',30,5);
INSERT INTO post values(6,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 6','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta3.jpg','Regata long',2,3);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta3.jpg',25.2,6);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta3.jpg',30,6);
INSERT INTO post values(7,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 7','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie1.jpg','Lingerie sem elastico',3,2);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie1.jpg',25.2,7);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie1.jpg',30,7);
INSERT INTO post values(8,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 8','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie2.jpg','Conjunto simples',3,1);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie2.jpg',25.2,8);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie2.jpg',30,8);
INSERT INTO post values(9,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 9','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara1.jpg','Máscara microfribra',4,3);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara1.jpg',25.2,9);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara1.jpg',30,9);
INSERT INTO post values(10,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 10','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara2.jpg','Máscara simples',4,2);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara2.jpg',25.2,10);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara2.jpg',30,10);
INSERT INTO post values(11,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 11','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara3.jpeg','Máscara fácil',4,3);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara3.jpeg',25.2,11);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara3.jpeg',30,11);
INSERT INTO post values(12,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 12','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido1.jpg','Vestido simples',5,1);
INSERT INTO post_item values(1,'Molde vestido P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido1.jpg',25.2,12);
INSERT INTO post_item values(2,'Molde vestido M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido1.jpg',30,12);
INSERT INTO post values(13,0,0,'2021-08-31 13:59:35.453600','Postagem de teste 13','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido2.jpg','Vestido festivo',5,2);
INSERT INTO post_item values(1,'Molde vestido P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido2.jpg',25.2,13);
INSERT INTO post_item values(2,'Molde vestido M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido2.jpg',30,13);
INSERT INTO followers values (1,3);
INSERT INTO followers values (2,3);
INSERT INTO followers values (3,1);