INSERT INTO users values(1, '2021-08-31 13:59:35.453600','Costureiro com vasta experiência em confecção de máscaras.','carlos.marangoni1@gmail.com','Carlos Eduardo Marangoni Mendes','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/carlos.jpg','carlos_marangoni');
INSERT INTO users values(2, '2021-08-30 13:59:35.453600','Revendedor de modelagens de vestido','carlos.marangoni2@gmail.com','Darlan Ricardo Marangoni da Silva','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/darlan.jpg','darlan_silva');
INSERT INTO users values(3, '2021-08-29 13:59:35.453600','Costureira com canal no youtube com mais de 1 milhão de inscritos.','carlos.marangoni13@gmail.com','Maria Silva','$2a$10$Z3.Vg4ERBJQIIVoHolb34OM90CFfKKBTcLrP6pTcuEEA/Fo6vr0Ha','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mari_costura.jpg','mari_costura');
INSERT INTO roles values(1,'ROLE_USER');
INSERT INTO roles values(2,'ROLE_ADMIN');
INSERT INTO roles values(3,'ROLE_CREATOR');
INSERT INTO users_roles values(1,2);
INSERT INTO users_roles values(1,3);
INSERT INTO users_roles values(2,1);
INSERT INTO users_roles values(3,3);
INSERT INTO category values (1,'CALÇA');
INSERT INTO category values (2,'CAMISETA');
INSERT INTO category values (3,'LINGERIE');
INSERT INTO category values (4,'MASCARA');
INSERT INTO category values (5,'VESTIDO');
INSERT INTO post values(1,4,1,'2021-08-31 13:59:35.453600','Calça jeans super fácil de fazer','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca1.png','Calça simples',1,1);
INSERT INTO post_item values(1,'Molde calca P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,1);
INSERT INTO post_item values(2,'Molde calca M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,1);
INSERT INTO post values(2,0,0,'2021-09-01 13:59:35.453600','Modelos de calça de couro feminino','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca2.jpg','Calça de couro',1,1);
INSERT INTO post_item values(1,'Molde calca P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',20,2);
INSERT INTO post_comments values(1,'Ótimo! Recomendo',4,1,2);
INSERT INTO post values(3,4,2,'2021-09-05 13:59:35.453600','Calça jeans flare, modelo fit','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/calca3.jpg','Calça jeans',1,2);
INSERT INTO post_comments(description,stars,post_id,user_id) values('Amei!',4,3,3);
INSERT INTO post_item values(1,'Molde calça flare P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',0,3);
INSERT INTO post values(4,0,0,'2021-08-31 13:59:35.453600','Camiseta slim fit para academia','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta1.jpg','Camiseta simples',2,1);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,4);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,4);
INSERT INTO post values(5,0,0,'2021-08-31 13:59:35.453600','Modelagem regata carnaval','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta2.jpg','Regata simples',2,2);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,5);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,5);
INSERT INTO post values(6,0,0,'2021-08-31 13:59:35.453600','Modelo de regata long para arrasar nas festas','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/camiseta3.jpg','Regata long',2,3);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,6);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,6);
INSERT INTO post values(7,0,0,'2021-08-31 13:59:35.453600','Molde conjunto discreto','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie1.jpg','Lingerie sem elastico',3,2);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,7);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,7);
INSERT INTO post values(8,0,0,'2021-08-31 13:59:35.453600','Conjunto de renda fácil de fazer','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/lingerie2.jpg','Conjunto simples',3,1);
INSERT INTO post_item values(1,'Molde sutiã P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,8);
INSERT INTO post_item values(2,'Molde sutiã M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,8);
INSERT INTO post values(9,0,0,'2021-08-31 13:59:35.453600','Máscara de fácil respiração, ideal para academias','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara1.jpg','Máscara microfribra',4,3);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,9);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,9);
INSERT INTO post values(10,0,0,'2021-08-31 13:59:35.453600','Máscara para uso no dia a dia','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara2.jpg','Máscara simples',4,2);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,10);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,10);
INSERT INTO post values(11,0,0,'2021-08-31 13:59:35.453600','Máscara discreta ótima para rosto triangular','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/mascara3.jpeg','Máscara fácil',4,3);
INSERT INTO post_item values(1,'Molde mascara P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,11);
INSERT INTO post_item values(2,'Molde mascara M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',30,11);
INSERT INTO post values(12,0,0,'2021-08-31 13:59:35.453600','Vestido discreto ideal para casamentos','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido1.jpg','Vestido simples',5,1);
INSERT INTO post_item values(1,'Molde vestido P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,12);
INSERT INTO post_item values(2,'Molde vestido M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/molde_3.png',30,12);
INSERT INTO post values(13,0,0,'2021-08-31 13:59:35.453600','Vestido perfeito para arrasar na noite','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/vestido2.jpg','Vestido festivo',5,2);
INSERT INTO post_item values(1,'Molde vestido P','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/modelagem2.jpg',25.2,13);
INSERT INTO post_item values(2,'Molde vestido M','https://spring-amazon-storage-molsew.s3.sa-east-1.amazonaws.com/molde_3.png',30,13);
INSERT INTO followers values (1,3);
INSERT INTO followers values (2,3);
INSERT INTO followers values (3,1);